### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by Ruriko** [ShugetsuSoft/pixivel-back#1]
Can I have instructions on how to install this and what are the prerequisites?

**Comment by EL-File4138** [comment]
Hi,

Sorry, but we currently do not provide documents for potential self-hoster. It's still in early development stage and is not ready for massive production use. Please seek other project instead.

**Comment by EL-File4138** [comment]
PS, your English intonation seems unnatural. Please use proper English for all kinds of communication. If you're willing to use Mandarin Chinese, just go ahead.
